In [8]:
import numpy as np
import scipy.sparse as sp
from scipy.sparse import coo_matrix, bmat

In [10]:
cs34 = sp.csr_matrix((3, 4), dtype=np.int8)

In [12]:
print(cs34.toarray())

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
